version: '3.9'
services:
  ml-models:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/my_code
    environment:
      - FLASK_APP=inference
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5050
    ports:
      - '5050:5050'
