# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ml-models-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ml-models
#   template:
#     metadata:
#       labels:
#         app: ml-models
#     spec:
#       containers:
#         - name: ml-models
#           image: lukemain/ml-models
#           ports:
#             - containerPort: 5050
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ml-models-cluster-ip-service
# spec:
#   type: ClusterIP
#   selector:
#     app: ml-models
#   ports:
#     - port: 5050
#       targetPort: 5050